#!/bin/sh
cd soomla-native/projects/unity-android-profile
./build_all
cd -
cd soomla-native/projects/unity-ios-profile
./build_all
cd -
./create_deploys
rm -rf build
mkdir build
cp *unitypackage build/
