#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
$DIR/submodules/build_all
$DIR/soomla-native/projects/unity-android-profile/build_all
$DIR/soomla-native/projects/unity-ios-profile/build_all
