#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

DEPLOY_PATH=out
PACKAGE_NAME=soomla-unity3d-profile.unitypackage
mkdir -p $DEPLOY_PATH
rm -f $DEPLOY_PATH/$PACKAGE_NAME

PROFILE_FILES=$(<file_list)

echo "creating unitypackage for SOOMLA Profile"

/Applications/Unity/Unity.app/Contents/MacOS/Unity \
  -batchmode \
  -logFile create_unity.log \
  -projectPath $PWD/../Soomla/ \
  -exportPackage \
    $PROFILE_FILES \
  $PWD/$DEPLOY_PATH/$PACKAGE_NAME \
  -quit

cd - > /dev/null
